Remove obsolete cache magisk img stuff

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -14,24 +14,22 @@
 ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
 $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
 
+# This path should work in any cases
+TMPDIR=/dev/tmp
+MOUNTPATH=$TMPDIR/magisk_img
+$BOOTMODE && IMG=/data/magisk_merge.img || IMG=/data/magisk.img
+INSTALLER=$TMPDIR/install
+MAGISKBIN=/data/magisk
+
 # DEFAULT PERMISSIONS
 umask 022
 
+# INITIAL CLEANUP
+rm -rf $TMPDIR 2>/dev/null
+mkdir -p $INSTALLER
+
 OUTFD=$2
 ZIP=$3
-
-ui_print() {
-  $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
-}
-
-is_mounted() {
-  if [ ! -z "$2" ]; then
-    cat /proc/mounts | grep $1 | grep $2, >/dev/null
-  else
-    cat /proc/mounts | grep $1 >/dev/null
-  fi
-  return $?
-}
 
 # GET INSTALL/UNINSTALL ACTION FROM ZIP NAME
 case $(basename $ZIP) in
@@ -39,33 +37,38 @@ case $(basename $ZIP) in
   *) ACTION=Install;;
 esac
 
-# MOUNT /DATA AND /CACHE TO ACCESS MAGISKBIN
-mount /data 2>/dev/null
-mount /cache 2>/dev/null
+# FUNCTIONS NEEDED BEFORE UTIL_FUNCTIONS IS CALLED
+get_outfd() {
+  readlink /proc/$$/fd/$OUTFD 2>/dev/null | grep /tmp >/dev/null
+  if [ "$?" -eq "0" ]; then
+    OUTFD=0
+    for FD in `ls /proc/$$/fd`; do
+      readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
+      if [ "$?" -eq "0" ]; then
+        ps | grep " 3 $FD " | grep -v grep >/dev/null
+        if [ "$?" -eq "0" ]; then
+          OUTFD=$FD
+          break
+        fi
+      fi
+    done
+  fi
+}
 
-# THIS PATH SHOULD WORK IN ANY CASES
-TMPDIR=/dev/tmp
-INSTALLER=$TMPDIR/install
-MOUNTPATH=$TMPDIR/magisk_img
+ui_print() {
+  $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
+}
 
+# GET OUTFD BEFORE ANY UI_PRINT STATEMENTS
+get_outfd
+
+# UNZIP FILES
 ui_print " "
 ui_print "Unzipping files..."
-
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $INSTALLER
 unzip -o "$ZIP" -d $INSTALLER 2>/dev/null
-
-if is_mounted /data; then
-  MAGISKBIN=/data/magisk
-  $BOOTMODE && IMG=/data/magisk_merge.img || IMG=/data/magisk.img
-else
-  IMG=/cache/magisk.img
-  MAGISKBIN=/cache/data_bin
-fi
 
 # LOAD UTILITY FUNCTIONS
 . $INSTALLER/common/unity-audmodlib/util_functions.sh
-get_outfd
 
 [ ! -f $INSTALLER/config.sh ] && abort "! Unable to extract zip file!"
 
@@ -704,11 +707,9 @@ if is_mounted /data; then
     standard_procedure
   fi
 elif is_mounted /cache; then
-  if [ ! -f "/cache/magisk.img" ]; then
-    system_install
-    script_install_logic
-    standard_procedure
-  fi
+  system_install
+  script_install_logic
+  standard_procedure
 else
   ui_print "! Unable to mount /data and /cache!"
   ui_print "! Aborting!"
